### ISSUE TITLE
Cargo.lock is missing

### ISSUE THREAD

**Issue by tesujimath** [devyn/nu_plugin_dbus#1]
Is that intentional?  I see a generic comment in `.gitignore` that suggests it may not be.

Further context:
+ https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control
+ https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html

**Comment by devyn** [comment]
I don't remember, but I don't see any reason not to add it. Thanks

**Comment by tesujimath** [comment]
I should have said, the reason for asking is that I'm packaging it for Nix, and the build rust package function in Nix really wants a Cargo.lock. 😁

**Comment by devyn** [comment]
Okay, should be good now then, unless you need me to publish it on cargo too.

I'll be putting out a new version tomorrow anyway as Nushell 0.93.0 will be releasing.

**Comment by tesujimath** [comment]
That's enough, thank you.

Excited about the 0.93.0 release! :partying_face:
