### ISSUE TITLE
Failed to decode with introspect

### ISSUE THREAD

**Issue by LordMZTE** [devyn/nu_plugin_dbus#2]
When running `dbus introspect --dest X /`, the plugin will respond with invalid data.

Example:
```
$ dbus introspect --dest org.freedesktop.Notifications /
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: invalid entry, duplicate keys are not allowed for `Record`
```

### System information
- OS: Arch Linux
- Nushell version: 0.93.0
- nu_plugin_dbus version: 0.6.0 from crates.io

**Comment by devyn** [comment]
Fixed, and released version 0.6.1. Thanks!
